/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TestSerialMsg'
 * message type.
 */

public class TestSerialMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 62;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = -1;

    /** Create a new TestSerialMsg of size 62. */
    public TestSerialMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TestSerialMsg of the given data_length. */
    public TestSerialMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg with the given data_length
     * and base offset.
     */
    public TestSerialMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store.
     */
    public TestSerialMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TestSerialMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TestSerialMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TestSerialMsg embedded in the given message
     * at the given base offset and length.
     */
    public TestSerialMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TestSerialMsg> \n";
      try {
        s += "  [nodeID=0x"+Long.toHexString(get_nodeID())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [message=";
        for (int i = 0; i < 60; i++) {
          s += "0x"+Long.toHexString(getElement_message(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeID
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeID' is signed (false).
     */
    public static boolean isSigned_nodeID() {
        return false;
    }

    /**
     * Return whether the field 'nodeID' is an array (false).
     */
    public static boolean isArray_nodeID() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeID'
     */
    public static int offset_nodeID() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeID'
     */
    public static int offsetBits_nodeID() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'nodeID'
     */
    public int get_nodeID() {
        return (int)getUIntBEElement(offsetBits_nodeID(), 16);
    }

    /**
     * Set the value of the field 'nodeID'
     */
    public void set_nodeID(int value) {
        setUIntBEElement(offsetBits_nodeID(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeID'
     */
    public static int size_nodeID() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeID'
     */
    public static int sizeBits_nodeID() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: message
    //   Field type: short[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'message' is signed (false).
     */
    public static boolean isSigned_message() {
        return false;
    }

    /**
     * Return whether the field 'message' is an array (true).
     */
    public static boolean isArray_message() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'message'
     */
    public static int offset_message(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 60) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'message'
     */
    public static int offsetBits_message(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 60) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'message' as a short[]
     */
    public short[] get_message() {
        short[] tmp = new short[60];
        for (int index0 = 0; index0 < numElements_message(0); index0++) {
            tmp[index0] = getElement_message(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'message' from the given short[]
     */
    public void set_message(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_message(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'message'
     */
    public short getElement_message(int index1) {
        return (short)getUIntBEElement(offsetBits_message(index1), 8);
    }

    /**
     * Set an element of the array 'message'
     */
    public void setElement_message(int index1, short value) {
        setUIntBEElement(offsetBits_message(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'message'
     */
    public static int totalSize_message() {
        return (480 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'message'
     */
    public static int totalSizeBits_message() {
        return 480;
    }

    /**
     * Return the size, in bytes, of each element of the array 'message'
     */
    public static int elementSize_message() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'message'
     */
    public static int elementSizeBits_message() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'message'
     */
    public static int numDimensions_message() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'message'
     */
    public static int numElements_message() {
        return 60;
    }

    /**
     * Return the number of elements in the array 'message'
     * for the given dimension.
     */
    public static int numElements_message(int dimension) {
      int array_dims[] = { 60,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'message' with a String
     */
    public void setString_message(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_message(i, (short)s.charAt(i));
         }
         setElement_message(i, (short)0); //null terminate
    }

    /**
     * Read the array 'message' as a String
     */
    public String getString_message() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,60)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_message(i) == (char)0) break;
             carr[i] = (char)getElement_message(i);
         }
         return new String(carr,0,i);
    }

}
