COMPONENT=BlinkPrintfAppC

# import the mote-to-serial printf library
# and setting its buffer size
CFLAGS += -I$(TINYOS_OS_DIR)/tos/lib/printf
CFLAGS += -DPRINTF_BUFFER=42

# import the path for the tinyos Make rules
include $(MAKERULES)
